site_name: UCD Physics Labs

site_url: https://physicslabs.ucd.ie/

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - md_in_html



nav:
  - Home: index.md
  - Information: 
    - Beech Hill: information/beech_hill.md
    - Stage 3: information/stage_3.md
    - Stage 4: information/stage_4.md
    - Dignity and Respect: information/d_and_r.md
  - Documentation:
    - Python:
      - Python Overview: documentation/python/python_overview.md
      - Get Python: documentation/python/get_python.md
      - Python Resources: documentation/python/python_resources.md
      - Coding Guidelines: documentation/python/coding_guidelines.md
      - Python How Tos: documentation/python/python_how_tos.md
    - DACQ:
        - DACQ Main Page: documentation/dacq/dacq_main.md
        - Data Aquisition Hints and Tips: documentation/dacq/data_aq_tips.md
        - DACQ General Concepts: documentation/dacq/dacq_concepts.md
        - NI USB-6008/6009: documentation/dacq/ni_usb_6000.md
        - RBD 9103 Picoammeter: documentation/dacq/rbd_1903.md
        - Fresnel Diffraction using Ultrasound: documentation/dacq/fresnel.md
        - Teensy Pulse Generator: documentation/dacq/teensy.md
        - IEEE-488: documentation/dacq/ieee-488.md
    - Data Analysis: documentation/data_analysis.md
    - Report Writing: documentation/report_writing.md

  
theme:
    name: material
    logo: imgs/UCD_logo_transparency.png
    favicon: imgs/UCD_logo_transparency_favicon_small.png
    features:
        - content.code.copy


extra:
    generator: true

copyright:  "&copy; 2025 UCD School of Physics"

repo_url: 