site_name: UCD Physics Labs

site_url: https://physicslabs.ucd.ie/

copyright:  "&copy; 2026 UCD School of Physics"


theme:
    name: material
    logo: imgs/UCD_logo_transparency.png
    favicon: imgs/UCD_logo_transparency_favicon_small.png
    features:
        - content.code.copy
        - navigation.sections


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - md_in_html



nav:
  - Home: index.md
  - Information: 
    - Beech Hill: information/beech_hill.md
    - Stage 3: information/stage_3.md
    - Stage 4: information/stage_4.md
    - Dignity and Respect: information/d_and_r.md
    - Safety: information/safety.md
  - Documentation:
    - Python:
      - Python Overview: documentation/python/python_overview.md
      - Get Python: documentation/python/get_python.md
      - Python Resources: documentation/python/python_resources.md
      - Coding Guidelines: documentation/python/coding_guidelines.md
      - Python How Tos: documentation/python/python_how_tos.md
    - DACQ:
        - DACQ Main Page: documentation/dacq/dacq_main.md
        - DACQ General Concepts: documentation/dacq/dacq_concepts.md
        - Data Aquisition Hints and Tips: documentation/dacq/data_aq_tips.md
        - NI USB-6008/6009: documentation/dacq/ni_usb_6000.md
        - RBD 9103 Picoammeter: documentation/dacq/rbd_1903.md
        - Fresnel Diffraction using Ultrasound: documentation/dacq/fresnel.md
        - Teensy Pulse Generator: documentation/dacq/teensy.md
        - IEEE-488: documentation/dacq/ieee-488.md
    - Falstad Circuit simulator: documentation/Falstad_circuit_sim.md
    - Data Analysis: documentation/data_analysis.md
    - Report Writing: documentation/report_writing.md

  

extra:
    generator: true

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_controls: True

# Breadcrumbs: pip install mkdocs-breadcrumbs-plugin
# Needs Information and Documentaion landing pages
#
#  - mkdocs-breadcrumbs-plugin:
#      delimiter: " / "       # Separator between segments
#      use_page_titles: true  # Show page titles instead of file paths
#      home_text: "Home"      # Customize the "Home" label
#      generate_home_index: true
